### ISSUE TITLE
Translate .txt file to .srt or videofile

### ISSUE THREAD

**Issue by CappiSteijns** [dbkynd/twitch-logger-docker#4]
Hi! First of all thanks you for this tool.

I was wondering if someone who uses this tool also managed to use the .txt log to make an .srt or videofile so they go together with the Twitch Video. 

Any solutions are welcome and hope I am in the right place to ask!

Thanks.

**Comment by DigibitDK** [comment]
I kind of struggling with the same. But since Twitch VODs do not have any timecode related to real timestamp, I think your idea is near impossible to achieve :(

**Comment by CappiSteijns** [comment]
> I kind of struggling with the same. But since Twitch VODs do not have any timecode related to real timestamp, I think your idea is near impossible to achieve :(

Using a different kind of program which does just what I want :) U can send a PM for the link, not sure if I'm allowed to past that here.

**Comment by DigibitDK** [comment]
As far as I know, there is no PM-option github :D Or I can't find it.
But send your link to github @ digibit.dk
